# Generated by Django 5.0.2 on 2024-02-21 13:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_description',
            field=tinymce.models.HTMLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_title',
            field=models.CharField(max_length=30),
        ),
    ]
