# Generated by Django 5.0.2 on 2024-03-18 05:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_blogpost_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_description',
            field=tinymce.models.HTMLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_title',
            field=models.CharField(max_length=32),
        ),
    ]
