# Generated by Django 5.0.2 on 2024-03-18 05:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_blogpost_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_description',
            field=tinymce.models.HTMLField(max_length=1500),
        ),
    ]
